# Site settings
title: Simon's Blog
email: simoncmilburn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Welcome to my blog. This will probably be a collection of random 
    things. Hope to update with current projects. 
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://scmilburn.com" # the base hostname & protocol for your site
twitter_username: bitcamp_roomba
github_username:  scmilburn

# Build settings
markdown: kramdown
